import type { Category, Order, OrderStatus, Product, StoreSettings } from "../types/catalog";
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? (import.meta.env.PROD ? "/api" : "http://localhost:4000/api");
type ApiResult<T> = { data: T; pagination?: { page: number; limit: number; total: number } };
async function request<T>(path: string, init: RequestInit = {}) { const response = await fetch(`${baseUrl}${path}`, { credentials: "include", headers: { "Content-Type": "application/json", ...init.headers }, ...init }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.message ?? "Permintaan API gagal."); } if (response.status === 204) return undefined as T; return response.json() as Promise<T>; }
export const api = {
  products: (params = "") => request<ApiResult<Product[]>>(`/products${params}`), product: (slug: string) => request<ApiResult<Product>>(`/products/${slug}`), categories: () => request<ApiResult<Category[]>>("/categories"), settings: () => request<ApiResult<StoreSettings>>("/settings"),
  createOrder: (payload: { buyerName: string; buyerPhone: string; buyerNote?: string; rawWhatsappMessage?: string; items: { productId: string; variantId?: string; qty: number }[] }) => request<ApiResult<Order>>("/orders", { method: "POST", body: JSON.stringify(payload) }),
  login: (email: string, password: string) => request<{ user: { id: string; email: string; name: string } }>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }), logout: () => request<void>("/auth/logout", { method: "POST" }), me: () => request<{ user: { id: string; email: string; name: string } }>("/auth/me"),
  adminProducts: (params = "") => request<ApiResult<Product[]>>(`/admin/products${params}`), createProduct: (data: Partial<Product>) => request<ApiResult<Product>>("/admin/products", { method: "POST", body: JSON.stringify(data) }), updateProduct: (id: string, data: Partial<Product>) => request<ApiResult<Product>>(`/admin/products/${id}`, { method: "PUT", body: JSON.stringify(data) }), deleteProduct: (id: string) => request<void>(`/admin/products/${id}`, { method: "DELETE" }), addVariant: (id: string, data: { label: string; priceDelta: number; stock: number }) => request(`/admin/products/${id}/variants`, { method: "POST", body: JSON.stringify(data) }),
  adminCategories: () => request<ApiResult<Category[]>>("/admin/categories"), createCategory: (data: Partial<Category>) => request<ApiResult<Category>>("/admin/categories", { method: "POST", body: JSON.stringify(data) }), updateCategory: (id: string, data: Partial<Category>) => request<ApiResult<Category>>(`/admin/categories/${id}`, { method: "PUT", body: JSON.stringify(data) }), deleteCategory: (id: string) => request<void>(`/admin/categories/${id}`, { method: "DELETE" }),
  adminOrders: (params = "") => request<ApiResult<Order[]>>(`/admin/orders${params}`), updateOrderStatus: (id: string, status: OrderStatus) => request<ApiResult<Order>>(`/admin/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }), adminSettings: () => request<ApiResult<StoreSettings>>("/admin/settings"), updateSettings: (data: Omit<StoreSettings, "logoUrl"> & { logoUrl?: string | null }) => request<ApiResult<StoreSettings>>("/admin/settings", { method: "PUT", body: JSON.stringify(data) }), dashboardStats: () => request<{ data: { products: number; categories: number; ordersToday: number; ordersThisMonth: number; revenueThisMonth: number } }>("/admin/dashboard/stats"),
  upload: async (files: File[]) => { const form = new FormData(); files.forEach((file) => form.append("images", file)); const response = await fetch(`${baseUrl}/uploads`, { method: "POST", credentials: "include", body: form }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).message ?? "Upload gagal."); return response.json() as Promise<{ data: { url: string; thumbnailUrl: string }[] }>; },
};
