import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

export const orderStatusEnum = pgEnum("order_status", ["baru", "diproses", "selesai", "batal"]);
export const productStatusEnum = pgEnum("product_status", ["draft", "aktif"]);
export const categories = pgTable("categories", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 80 }).notNull(), slug: varchar("slug", { length: 100 }).notNull().unique(), icon: varchar("icon", { length: 60 }), sortOrder: integer("sort_order").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull() }).enableRLS();
export const products = pgTable("products", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 180 }).notNull(), slug: varchar("slug", { length: 200 }).notNull().unique(), description: text("description"), price: integer("price").notNull(), stock: integer("stock").default(0).notNull(), categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }), images: jsonb("images").$type<string[]>().default([]).notNull(), status: productStatusEnum("status").default("aktif").notNull(), deletedAt: timestamp("deleted_at"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (t) => ({ idxName: index("idx_products_name").on(t.name) })).enableRLS();
export const productVariants = pgTable("product_variants", { id: uuid("id").defaultRandom().primaryKey(), productId: uuid("product_id").references(() => products.id, { onDelete: "cascade" }).notNull(), label: varchar("label", { length: 80 }).notNull(), priceDelta: integer("price_delta").default(0).notNull(), stock: integer("stock").default(0).notNull() }).enableRLS();
export const orders = pgTable("orders", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 32 }).notNull().unique(), buyerName: varchar("buyer_name", { length: 120 }).notNull(), buyerPhone: varchar("buyer_phone", { length: 25 }).notNull(), buyerNote: text("buyer_note"), total: integer("total").notNull(), status: orderStatusEnum("status").default("baru").notNull(), source: varchar("source", { length: 20 }).default("whatsapp").notNull(), rawWhatsappMessage: text("raw_whatsapp_message"), createdAt: timestamp("created_at").defaultNow().notNull() }).enableRLS();
export const orderItems = pgTable("order_items", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), productId: uuid("product_id").references(() => products.id, { onDelete: "set null" }), productName: varchar("product_name", { length: 180 }).notNull(), variantLabel: varchar("variant_label", { length: 120 }), price: integer("price").notNull(), qty: integer("qty").notNull(), subtotal: integer("subtotal").notNull() }).enableRLS();
export const adminUsers = pgTable("admin_users", { id: uuid("id").defaultRandom().primaryKey(), email: varchar("email", { length: 120 }).notNull().unique(), name: varchar("name", { length: 100 }).notNull(), passwordHash: varchar("password_hash", { length: 200 }).notNull(), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull() }).enableRLS();
export const storeSettings = pgTable("store_settings", { id: varchar("id", { length: 20 }).primaryKey().default("singleton"), storeName: varchar("store_name", { length: 120 }).notNull(), logoUrl: text("logo_url"), whatsappNumber: varchar("whatsapp_number", { length: 20 }).notNull(), address: text("address"), openHours: varchar("open_hours", { length: 120 }), messageTemplate: text("message_template").notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }).enableRLS();
