import { Router } from "express";
import { and, asc, count, desc, eq, ilike, inArray, isNull, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "../db/client.js";
import { categories, orderItems, orders, productVariants, products, storeSettings } from "../db/schema.js";
import { formatOrderCode, normalizePhone } from "../lib/helpers.js";
import { validate } from "../middleware/validate.js";
export const publicRouter = Router();
const cache = (_req: any, res: any, next: any) => { res.set("Cache-Control", "public, max-age=60"); next(); };
async function decorate(rows: typeof products.$inferSelect[]) { const ids = rows.map((p) => p.id); const variants = ids.length ? await db.select().from(productVariants).where(inArray(productVariants.productId, ids)) : []; return rows.map((product) => ({ ...product, variants: variants.filter((variant) => variant.productId === product.id) })); }
publicRouter.get("/products", cache, validate(z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(24).default(24), q: z.string().trim().max(100).optional(), category: z.string().trim().max(100).optional() }), "query"), async (req, res, next) => { try { const { page, limit, q, category } = req.query as any; const categoryRow = category ? await db.query.categories.findFirst({ where: eq(categories.slug, category) }) : undefined; if (category && !categoryRow) return res.json({ data: [], pagination: { page, limit, total: 0 } }); const where = and(eq(products.status, "aktif"), isNull(products.deletedAt), q ? ilike(products.name, `%${q}%`) : undefined, categoryRow ? eq(products.categoryId, categoryRow.id) : undefined); const [rows, totalRows] = await Promise.all([db.select().from(products).where(where).orderBy(desc(products.createdAt)).limit(limit).offset((page - 1) * limit), db.select({ value: count() }).from(products).where(where)]); res.json({ data: await decorate(rows), pagination: { page, limit, total: totalRows[0]?.value ?? 0 } }); } catch (error) { next(error); } });
publicRouter.get("/products/:slug", cache, validate(z.object({ slug: z.string().min(1).max(200) }), "params"), async (req, res, next) => { try { const product = await db.query.products.findFirst({ where: and(eq(products.slug, req.params.slug), eq(products.status, "aktif"), isNull(products.deletedAt)) }); if (!product) return res.status(404).json({ message: "Produk tidak ditemukan." }); res.json({ data: (await decorate([product]))[0] }); } catch (error) { next(error); } });
publicRouter.get("/categories", cache, async (_req, res, next) => { try { res.json({ data: await db.select().from(categories).orderBy(asc(categories.sortOrder), asc(categories.name)) }); } catch (error) { next(error); } });
publicRouter.get("/settings", async (_req, res, next) => { try { const settings = await db.query.storeSettings.findFirst({ where: eq(storeSettings.id, "singleton") }); if (!settings) return res.status(404).json({ message: "Pengaturan toko belum tersedia." }); res.json({ data: settings }); } catch (error) { next(error); } });
const orderSchema = z.object({ buyerName: z.string().trim().min(2).max(120), buyerPhone: z.string().min(8).max(25), buyerNote: z.string().max(2000).optional().default(""), rawWhatsappMessage: z.string().max(12000).optional(), items: z.array(z.object({ productId: z.string().uuid(), variantId: z.string().uuid().optional(), qty: z.number().int().min(1).max(99) })).min(1).max(30) });
publicRouter.post("/orders", validate(orderSchema), async (req, res, next) => { try { const payload = req.body as z.infer<typeof orderSchema>; const phone = normalizePhone(payload.buyerPhone); if (!/^62\d{8,12}$/.test(phone)) return res.status(400).json({ message: "Nomor WhatsApp harus menggunakan format Indonesia yang valid." }); const productIds = [...new Set(payload.items.map((item) => item.productId))]; const dbProducts = await db.select().from(products).where(and(inArray(products.id, productIds), eq(products.status, "aktif"), isNull(products.deletedAt))); if (dbProducts.length !== productIds.length) return res.status(400).json({ message: "Satu atau lebih produk sudah tidak tersedia." }); const variantIds = payload.items.flatMap((item) => item.variantId ? [item.variantId] : []); const variants = variantIds.length ? await db.select().from(productVariants).where(inArray(productVariants.id, variantIds)) : []; const lines = payload.items.map((item) => { const product = dbProducts.find((row) => row.id === item.productId)!; const variant = item.variantId ? variants.find((row) => row.id === item.variantId && row.productId === product.id) : undefined; if (item.variantId && !variant) throw new Error("Varian produk tidak valid."); const available = variant ? variant.stock : product.stock; if (item.qty > available) throw new Error(`Stok ${product.name} tidak mencukupi.`); const price = product.price + (variant?.priceDelta ?? 0); return { productId: product.id, productName: product.name, variantLabel: variant?.label, price, qty: item.qty, subtotal: price * item.qty }; }); const total = lines.reduce((sum, item) => sum + item.subtotal, 0); const dayPrefix = formatOrderCode().slice(0, 12); const todayCount = await db.select({ value: count() }).from(orders).where(sql`${orders.code} like ${dayPrefix + "%"}`); const code = formatOrderCode(new Date(), (todayCount[0]?.value ?? 0) + 1); const created = await db.transaction(async (tx) => { const [order] = await tx.insert(orders).values({ code, buyerName: payload.buyerName, buyerPhone: phone, buyerNote: payload.buyerNote, total, rawWhatsappMessage: payload.rawWhatsappMessage }).returning(); await tx.insert(orderItems).values(lines.map((item) => ({ ...item, orderId: order.id }))); return order; }); res.status(201).json({ data: { ...created, items: lines } }); } catch (error) { next(error); } });
