import { Edit3, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "../../components/ui/button";
import { Dialog } from "../../components/ui/dialog";
import { Input } from "../../components/ui/input";
import { TableWrap, Td, Th } from "../../components/ui/table";
import { api } from "../../lib/api";
import { makeSlug } from "../../lib/utils";
import type { Category } from "../../types/catalog";

export function CategoriesPage() {
  const client = useQueryClient(); const [editing, setEditing] = useState<Category | null>(null); const [modal, setModal] = useState(false);
  const { data: rows = [], isLoading, error } = useQuery({ queryKey: ["admin", "categories"], queryFn: () => api.adminCategories().then((result) => result.data) });
  const refresh = () => client.invalidateQueries({ queryKey: ["admin", "categories"] });
  const saveCategory = useMutation({ mutationFn: (value: Category) => rows.some((row) => row.id === value.id) ? api.updateCategory(value.id, value) : api.createCategory(value), onSuccess: () => { refresh(); setModal(false); }, onError: (saveError) => alert((saveError as Error).message) });
  const removeCategory = useMutation({ mutationFn: api.deleteCategory, onSuccess: refresh, onError: (removeError) => alert((removeError as Error).message) });
  const startAdd = () => { setEditing({ id: crypto.randomUUID(), name: "", slug: "", icon: "Tag", sortOrder: rows.length + 1 }); setModal(true); };
  return <div><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-gray-500">Katalog</p><h1 className="mt-1 text-2xl font-bold">Kelola Kategori</h1></div><Button onClick={startAdd}><Plus size={16}/>Tambah Kategori</Button></div><p className="mt-3 text-sm text-gray-500">Kategori tersimpan ke database dan langsung dipakai oleh katalog publik.</p>{error && <p className="mt-4 rounded-md bg-red-50 p-3 text-xs font-bold text-danger">{(error as Error).message}</p>}<TableWrap className="mt-6"><thead><tr><Th>Urutan</Th><Th>Nama Kategori</Th><Th>Slug</Th><Th>Ikon</Th><Th><span className="sr-only">Aksi</span></Th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><Td><span className="font-mono">{row.sortOrder}</span></Td><Td><p className="font-bold">{row.name}</p></Td><Td><span className="font-mono text-xs text-gray-500">/{row.slug}</span></Td><Td className="text-xs">{row.icon}</Td><Td><div className="flex justify-end gap-1"><button onClick={() => { setEditing(row); setModal(true); }} className="rounded-md p-2 hover:bg-gray-100"><Edit3 size={16}/></button><button disabled={removeCategory.isPending} onClick={() => removeCategory.mutate(row.id)} className="rounded-md p-2 text-gray-500 hover:bg-red-50 hover:text-danger"><Trash2 size={16}/></button></div></Td></tr>)}{!rows.length && <tr><Td colSpan={5} className="py-10 text-center text-gray-500">{isLoading ? "Memuat kategori…" : "Belum ada kategori."}</Td></tr>}</tbody></TableWrap><Dialog open={modal} onClose={() => setModal(false)} title={editing && rows.some((row) => row.id === editing.id) ? "Edit Kategori" : "Tambah Kategori"}>{editing && <form onSubmit={(event) => { event.preventDefault(); saveCategory.mutate(editing); }} className="space-y-4"><label className="block text-xs font-bold">Nama kategori<Input required className="mt-2" value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value, slug: makeSlug(event.target.value) })}/></label><label className="block text-xs font-bold">Slug<Input required className="mt-2 font-mono text-xs" value={editing.slug} onChange={(event) => setEditing({ ...editing, slug: makeSlug(event.target.value) })}/></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-bold">Ikon<Input className="mt-2" value={editing.icon} onChange={(event) => setEditing({ ...editing, icon: event.target.value })}/></label><label className="block text-xs font-bold">Urutan<Input className="mt-2 font-mono" type="number" value={editing.sortOrder} onChange={(event) => setEditing({ ...editing, sortOrder: Number(event.target.value) })}/></label></div><Button className="w-full" type="submit" disabled={saveCategory.isPending}>{saveCategory.isPending ? "Menyimpan…" : "Simpan Kategori"}</Button></form>}</Dialog></div>;
}
