import { Edit3, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Badge } from "../../components/ui/badge";
import { Input } from "../../components/ui/input";
import { TableWrap, Td, Th } from "../../components/ui/table";
import { api } from "../../lib/api";
import { queryKeys } from "../../lib/queries";
import { formatRupiah } from "../../lib/utils";
export function ProductsPage() { const [term, setTerm] = useState(""); const [categoryId, setCategoryId] = useState(""); const client = useQueryClient(); const { data = [], isLoading } = useQuery({ queryKey: queryKeys.adminProducts(), queryFn: () => api.adminProducts().then((x) => x.data) }); const { data: categories = [] } = useQuery({ queryKey: ["admin", "categories"], queryFn: () => api.adminCategories().then((x) => x.data) }); const remove = useMutation({ mutationFn: api.deleteProduct, onSuccess: () => client.invalidateQueries({ queryKey: queryKeys.adminProducts() }) }); const filtered = useMemo(() => data.filter((p) => p.name.toLowerCase().includes(term.toLowerCase()) && (!categoryId || p.categoryId === categoryId)), [term, categoryId, data]); return <div><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-gray-500">Katalog</p><h1 className="mt-1 text-2xl font-bold">Kelola Produk</h1></div><Link to="/admin/produk/baru" className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-white"><Plus size={16}/>Tambah Produk</Link></div><div className="mt-6 flex gap-3 rounded-lg border bg-white p-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16}/><Input value={term} onChange={(e) => setTerm(e.target.value)} className="pl-9" placeholder="Cari nama produk..."/></div><select value={categoryId} onChange={(e) => setCategoryId(e.target.value)} className="h-10 rounded-lg border px-3 text-sm"><option value="">Semua kategori</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><TableWrap className="mt-4"><thead><tr><Th>Produk</Th><Th>Kategori</Th><Th>Harga</Th><Th>Stok</Th><Th>Status</Th><Th>Aksi</Th></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><Td><div className="flex items-center gap-3"><img src={product.images[0]} className="h-10 w-10 rounded-md border object-cover"/><p className="max-w-48 truncate font-bold">{product.name}</p></div></Td><Td className="text-xs">{categories.find((c) => c.id === product.categoryId)?.name}</Td><Td><span className="font-mono text-xs font-bold">{formatRupiah(product.price)}</span></Td><Td>{product.stock === 0 ? <Badge variant="danger">Habis</Badge> : product.stock}</Td><Td><Badge variant={product.status === "aktif" ? "success" : "neutral"}>{product.status}</Badge></Td><Td><div className="flex gap-1"><Link to={`/admin/produk/${product.id}/edit`} className="p-2"><Edit3 size={16}/></Link><button onClick={() => remove.mutate(product.id)} className="p-2 text-danger"><Trash2 size={16}/></button></div></Td></tr>)}{!filtered.length && <tr><Td colSpan={6} className="py-10 text-center text-gray-500">{isLoading ? "Memuat produk…" : "Tidak ada produk."}</Td></tr>}</tbody></TableWrap></div>; }
