import { LogIn, Menu, Search, ShoppingBag, X } from "lucide-react";
import { Link, Outlet, useNavigate, useSearchParams } from "react-router-dom";
import { useState } from "react";
import { useCartStore } from "../../store/cartStore";
import { storeSettings } from "../../mocks/storeSettings";
import { Input } from "../ui/input";
import { useSettings } from "../../lib/queries";
import { StoreLogo } from "./StoreLogo";

export function PublicLayout() {
  const count = useCartStore((state) => state.totalItems()); const { data: savedSettings } = useSettings(); const settings = savedSettings ?? storeSettings; const [open, setOpen] = useState(false); const [params] = useSearchParams(); const navigate = useNavigate(); const [query, setQuery] = useState(params.get("q") ?? ""); const links = [["Katalog", "/"], ["Tentang", "/tentang"], ["FAQ", "/faq"]];
  const submit = (event: React.FormEvent) => { event.preventDefault(); navigate(query ? `/?q=${encodeURIComponent(query)}` : "/"); setOpen(false); };
  return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-border bg-white/95 backdrop-blur"><div className="page-container flex h-16 items-center gap-3"><button onClick={() => setOpen(!open)} className="rounded-md p-2 lg:hidden" aria-label="Buka menu">{open ? <X size={20}/> : <Menu size={20}/>}</button><Link to="/" className="flex shrink-0 items-center gap-2 font-heading text-base font-bold"><StoreLogo logoUrl={settings.logoUrl} className="h-8 w-8"/><span className="hidden sm:inline">{settings.storeName}</span></Link><form onSubmit={submit} className="relative ml-auto hidden max-w-md flex-1 md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16}/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari produk..." className="pl-9"/></form><nav className="hidden items-center gap-5 lg:flex">{links.map(([label, to]) => <Link key={to} to={to} className="text-xs font-semibold text-gray-600 hover:text-primary">{label}</Link>)}</nav><Link to="/keranjang" className="relative rounded-md p-2 transition hover:bg-gray-100" aria-label="Keranjang"><ShoppingBag size={20}/>{count > 0 && <span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-primary px-1 text-[10px] font-bold text-white animate-cart-pop">{count}</span>}</Link></div>{open && <div className="border-t border-border bg-white px-4 py-3 lg:hidden"><form onSubmit={submit} className="relative mb-3"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16}/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari produk..." className="pl-9"/></form><div className="flex flex-wrap gap-4">{links.map(([label, to]) => <Link key={to} to={to} onClick={() => setOpen(false)} className="text-xs font-bold">{label}</Link>)}</div></div>}</header><main><Outlet/></main><footer className="mt-12 border-t border-border bg-white"><div className="page-container flex flex-col gap-2 py-7 text-xs text-gray-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} {settings.storeName}. Belanja praktis, pesan langsung.</p><div className="flex items-center gap-4"><p>{settings.openHours}</p><Link to="/admin/login" title="Login Pengelola" aria-label="Login Pengelola" className="group inline-flex items-center gap-1 rounded-md p-1 text-gray-500 transition hover:bg-gray-100 hover:text-primary"><LogIn size={16}/><span className="max-w-0 overflow-hidden whitespace-nowrap text-[11px] font-bold opacity-0 transition-all duration-150 group-hover:max-w-32 group-hover:opacity-100">Login Pengelola</span></Link></div></div></footer></div>;
}
